#!/usr/bin/env python3

import os
import sys
import argparse
import json
from jira import JIRA

# put your info in config.py
import config

################################################################################
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--age", default="365d")
parser.add_argument("dumpfile")
args = parser.parse_args()

print("Connecting to jira: " + config.jira_url)
jira = JIRA(config.jira_url, auth=config.jira_auth)

def log_issue(issue):
    print("{}: {}".format(issue.key, issue.fields.summary))
    with open(args.dumpfile, "a") as outfile:
        outfile.write(json.dumps(issue.raw))
        outfile.write("\n")

def dump_project(project):
    count = 0
    # jira SDK is ignoring maxResults > 1000, grrr
    jql = "project = \"{}\" AND status != Closed AND updated > -{}".format(project, args.age)
    print(project + " JQL >>> " + jql)
    for issue in jira.search_issues(jql, maxResults=1000):
        log_issue(issue)
        count = count + 1
    print("=> {} {} issues TOTAL\n".format(project, count))
    
for project in jira.projects():
    dump_project(project)
